#!/bin/bash

# Extract fields using jq
name=$(jq -r '.name' data.json | sed 's/.*/\u&/')
height=$(jq -r '.height' data.json | awk '{printf "%.1f", $1/10}')
weight=$(jq -r '.weight' data.json | awk '{printf "%.0f", $1/10}')
type=$(jq -r '.types[0].type.name' data.json | sed 's/.*/\u&/')

# Output in required format
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."
